### ISSUE TITLE
ML.NET porovnanie dat

### ISSUE THREAD

**Issue by KelloTomas** [Garickson96/Bc_Erik_Kostelansky_analyzaVlastnostiVlakovejSupravyMLDotNet#4]
Skus si spravit tabulku ake vysledky dostanes(chybu R2) ked trenujes na 1. testujes na 2., 3, 4, 5, 6, 7

**Comment by KelloTomas** [comment]
Potom trenuj na 2. testuj na 1, 3, 4, 5, 6, 7
trenuj 3 testuj 1,2,4,5,6,7

A v podstate z tohto ti vyjde tabulka, to bude moct ist do dokumentacia a opisat preco to tak vyslo (niekde dosiahnes hodne zle vysledky) S tym budeme dalej pracovat. Ked to budes mat, napis mi

**Comment by Garickson96** [comment]
17668985dd5b284536863285dff357b4ea90e009
6e3dbe7509d319cd5b0c51867e29350d78687551
